### ISSUE TITLE
Groups2TeamDrive?

### ISSUE THREAD

**Issue by mattmol** [ahochsteger/gmail2gdrive#15]
Hi All
This works great, but I have a new challenge.
I would like to move all attachments to a Google Group address to a team drive.

Basically, I have a virtual fax machine going to a Group.  I want those attachments to be automatically inserted into a Team Drive named Faxes.

Any help would be appreciated.

Thanks!

**Comment by TimmieSheetz** [comment]
I'd like to see that capability as well.

Thanks.

**Comment by ianhyzy** [comment]
Seconding Team Drive support.

**Comment by ahochsteger** [comment]
I had a look at the [Groups Service API](https://developers.google.com/apps-script/reference/groups/) and it seems to be quite limited so that it won't be possible to do anything like that using Google Groups as source of emails instead of Gmail (if I understood the use case correctly).

The API misses the following functionality that is essential to support something similar:
* No way to search for messages as in Gmail
* No way to mark already processed messages as in Gmail (e.g. using labels)

The only way I see is to process the emails that are sent to Gmail using Google Groups.
But note that currently this may not be supported due to the fact that marking emails as processed is done using labels which can only be attached to a thread and not to a single message (see [section "Limitations" in README.md](https://github.com/ahochsteger/gmail2gdrive/blob/master/README.md#limitations)).

I will close this issue as I don't see an easy way to support it.
Feel free to open a separate issue for the mentioned limitation (threads vs. messages) but this may require some conceptual changes to the way Gmail2GDrives marks already processed messages.
